#!/usr/bin/env python3
#-*- coding: utf-8 -*-
#

from petsys import daqd
from time import sleep
import sys
import logging
logging.basicConfig(level=logging.INFO, filename='output.log')

daqd = daqd.Connection()

logging.info("--- DAQ PORTS ---") 
for portID in daqd.getActivePorts():
	logging.info("DAQ Port %2d: " % portID, "%12d transmitted %12d received (%d errors)" % daqd.getPortCounts(portID))

logging.info("--- CONNECTED UNITSs ---")
for portID, slaveID in daqd.getActiveUnits():
	mtx, mrx, mrxBad, slaveOn, stx, srx, srxBad = daqd.getFEBDCount1(portID, slaveID)
	unit_variant = daqd.read_config_register(portID, slaveID, 16, 0x0022)

	if (daqd.read_config_register(portID, slaveID, 64, 0xFFF8) & 0x1) != 0:
		# This unit has the version code
		unit_version = "0x%016X" % daqd.read_config_register(portID, slaveID, 64, 0xFFF0)
	else:
		unit_version = "n/a"


	if daqd.read_config_register(portID, slaveID, 1, 0x0000) == 1:
		# This is a FEB/D
		fem_variant = daqd.read_config_register(portID, slaveID, 16, 0x0002)
		logging.info("Unit (%2d, %2d): FEB/D type:%04X fem:%04X ver:%s\n" % (portID, slaveID, unit_variant, fem_variant, unit_version), end=' ')


	elif daqd.read_config_register(portID, slaveID, 1, 0x0001) == 1:
		logging.info("Unit (%2d, %2d): CLK&TGR type:%04X ver:%s\n" % (portID, slaveID, unit_variant, unit_version), end=' ')
	else:
		sys.stderr.write("ERROR: UNIT (%2d, %2d) is of unknown type!\n" % (portID, slaveID))
		exit(1)

	logging.info("  MASTER link %12d transmitted %12d received (%d errors)" % (mtx, mrx, mrxBad))
	if slaveOn:
		logging.info("  SLAVE  link %12d transmitted %12d received (%d errors)" % (stx, srx, srxBad))
	else:
		logging.info("  SLAVE  link off")
