#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from petsys import daqd, fe_temperature, config
import time
import zmq
import signal

context = zmq.Context()
socket = context.socket(zmq.PUB)
socket.bind("tcp://172.16.32.214:2002")
class SignalListener:
    terminate = False
    def __init__(self):
        signal.signal(signal.SIGINT, self.exit)
        signal.signal(signal.SIGTERM, self.exit)
    def exit(self, *args):
        self.terminate = True
def main():
    connection = daqd.Connection()
    connection.initializeSystem()
    sensor_list = fe_temperature.get_sensor_list(connection)
    if sensor_list is []:
        print("WARNING: No sensors found. Check connections and power.")
        return 1
    listener = SignalListener()
    while not listener.terminate:
        r = {}
        for sensor in sensor_list:
            if sensor.get_location()[4] == "asic":
                # Two ASICs per FEB/A
                r[f"ch{sensor.get_location()[2]}_{sensor.get_location()[3]}_T"] = sensor.get_temperature()
        r['timestamp'] = time.time()
        socket.send_json(r)
        time.sleep(5) # 5 seconds
    return 0

if __name__ == '__main__':
	main()
